services:
  - type: worker
    name: discord-bot
    runtime: python
    repo: https://github.com/your/repo
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
